package models
{
  public class DataModel
  {
    private function DataModel()
    {
      
    }
    public static const navProvider:Array = [
        "Accordion",
        "Action Bar",
        "Action Button",
        "Action Group",
        "Action Menu",
        "Alert",
        "Asset",
        "Asset List",
        "Avatar",
        "Banner",
        "Bar Loader",
        "Breadcrumbs",
        "Button",
        "Button Group",
        "Calendar",
        "Card",
        "Card - Asset preview",
        "Card - Gallery",
        "Checkbox",
        "Circle Loader",
        "Clear Button",
        "Coach Mark",
        "Color Picker",
        "Color Handle",
        "Color Loupe",
        "Color Slider",
        "Color Wheel",
        "Combobox",
        "Cycle Button",
        "Date Picker",
        "Dial",
        "Dialog",
        "Divider",
        "Drop Indicator",
        "Dropzone",
        "Field Group",
        "Field Label",
        "Form",
        "Illustrated Message",
        "Inline Alert",
        "Label",
        "Link",
        "Logic Button",
        "Menu",
        "Meter",
        "Miller Columns",
        "Page",
        "Pagination - Button Style",
        "Pagination - Explicit",
        "Pagination - Page",
        "Picker",
        "Popover",
        "Quick Actions",
        "Radio",
        "Rating",
        "Search",
        "Search Within",
        "Side Navigation",
        "Slider",
        "Split Button",
        "SplitView",
        "Status Light",
        "Steplist",
        "Stepper",
        "Switch",
        "Table",
        "Tabs",
        "Tags",
        "Tag Field",
        "Text Area",
        "Text Field",
        "Thumbnail",
        "Toast",
        "Tooltip",
        "Tree View",
        "Typography",
        "Typography (Internationalized)",
        "Typography Body",
        "Typography Code",
        "Typography Detail",
        "Typography Heading",
        "Well"
    ];
  }
}