package models
{
  public class DataModel
  {
    private function DataModel()
    {
      
    }
    public static const navProvider:Array = [
        "Accordion",
        "Action Bar",
        "Action Button",
        "Action Menu",
        "Alert",
        "Asset",
        "Asset List",
        "Avatar",
        "Banner",
        "Bar Loader",
        "Breadcrumbs",
        "Button",
        "Button Group",
        "Calendar",
        "Card",
        "Card - Asset preview",
        "Card - Gallery",
        "Checkbox",
        "Circle Loader",
        "Clear Button",
        "Coach Mark",
        "Color Area",
        "Color Handle",
        "Color Loupe",
        "Color Slider",
        "Combobox",
        "Cycle Button",
        "Date Picker",
        "Dial",
        "Dialog",
        "Divider",
        "Drop Indicator",
        "Dropzone",
        "Field Group",
        "Field Label",
        "Form",
        "Illustrated Message",
        "Label",
        "Link",
        "Logic Button",
        "Menu",
        "Meter",
        "Miller Columns",
        "Page",
        "Pagination - Button Style",
        "Pagination - Explicit",
        "Pagination - Page",
        "Picker",
        "Popover",
        "Quick Actions",
        "Radio",
        "Rating",
        "Search",
        "Search Within",
        "Side Navigation",
        "Slider",
        "Split Button",
        "SplitView",
        "Status Light",
        "Steplist",
        "Stepper",
        "Switch",
        "Table",
        "Tabs",
        "Tags",
        "Text Area",
        "Text Field",
        "Thumbnail",
        "Toast",
        "Tooltip",
        "Tree View",
        "Typography (Internationalized)",
        "Typography",
        "Typography Body",
        "Typography Code",
        "Typography Detail",
        "Typography Heading",
        "Well"
    ];
  }
}